export interface Vehicle {
    stock_id: number
    company_id: number
    stock_code: string
    mmcode: number
    variant: string
    series: string
    make: string
    selling_price: number
    year: number
    mileage: number
    date_created: Date
    date_updated: Date
    description: string
    condition: string
    colour: string
    province: string
    suburb: string
    location: string
    extras_csv: string
    body_type: string
    finance_url: string
    video_url: string
    image_count: number
    used: boolean
    url1: string
    url2: string
    url3: string
    url4: string
    url5: string
    url6: string
    url7: string
    url8: string
    url9: string
    url10: string
    url11: string
    url12: string
    url13: string
    url14: string
    url15: string
    url16: string
    url17: string
    url18: string
    url19: string
    url20: string
    fuel_type: string
    height: number
    width: number
    length: number
    gears: number
    transmission: string
    cooling: string
    front_tyre_size: string
    rear_tyre_size: string
    axle_configuration: string
    tare: number
    gvm: number
    gcm: any
    seats: number
    doors: number
    kilowatts: number
    cubic_capacity: number
    fuel_tank_size: number
    co2: number
    premium: number
  }
  